### ISSUE TITLE
Unexpected "No Transpose" behaviour

### ISSUE THREAD

**Issue by jd-foster** [xrq-phys/BLIS.jl#6]
Thanks for putting together this package.

I wanted to check that you were aware that the `'C'` ("Conjugate Transpose) option when applied to real matrices has the same behaviour as the `'N'` ("No Transpose") option, and when applied to complex matrices, it is the same as just conjugating the entries but **without transpose**.
My expectation follows from Reference BLAS notes: http://www.netlib.org/blas/blasqr.pdf
and here: http://www.math.utah.edu/software/lapack/lapack-blas/zgemm.html

I guess the reason for the behaviour is clear from the definition in `types.jl`:
```julia
char_to_trans = Dict( 'N' => BLIS_NO_TRANSPOSE,
                      'n' => BLIS_NO_TRANSPOSE,
                      'T' => BLIS_TRANSPOSE,
                      't' => BLIS_TRANSPOSE,
                      'C' => BLIS_CONJ_NO_TRANSPOSE,
                      'c' => BLIS_CONJ_NO_TRANSPOSE )
```
Here is a MWE.
```julia
A = Float64[1. 2.; 3. 4.]
B = Float64[5. 6.; 7. 8.]
C = zeros(Float64, 2, 2);
```
```julia
# # Note! : 'C' is equivalent to 'N', not 'T' on real matrices:
BLIS.BLASInterface.gemm!('N', 'C', 1.0, A, B, 1.0, copy(C)) == BLIS.BLASInterface.gemm!('N', 'N', 1.0, A, B, 1.0, copy(C))
# true
```
I was expecting
```julia
BLIS.BLASInterface.gemm!('N', 'C', 1.0, A, B, 1.0, copy(C)) == BLIS.BLASInterface.gemm!('N', 'T', 1.0, A, B, 1.0, copy(C))
# false : not expected
```

But now I see that LinearAlgebra.BLAS seems to follow the same convention too!
```julia
A = Matrix(UniformScaling(1.0+0.0im), 2, 2)
B = rand(ComplexF64, 2, 2);
@assert LinearAlgebra.BLAS.gemm('N','N',A,B) == B
@assert LinearAlgebra.BLAS.gemm('N','T',A,B) == transpose(B)
@assert LinearAlgebra.BLAS.gemm('N','C',A,B) == conj(B)
@assert LinearAlgebra.BLAS.gemm('N','C',A, Matrix(B')) == transpose(B)
```

Clarification welcome!

**Comment by xrq-phys** [comment]
Hi!

Thank you for raising this issue.

I'm afraid this is completely my mistake.

`C` stands for `CONJUGATE_TRANSPOSE` always.

The reason for `LinearAlgebra.BLAS.gemm`'s treating 'C' as `CONJUGATE` is that import `BLIS` overrides `LinearAlgebra.BLAS` subroutines so that one is always calling the BLIS backend.

I'm also considering giving an option to not override but that seems to require altering the compilation procedure.

Anyway, sorry for the confusion.

**Comment by jd-foster** [comment]
That was very quick; thanks. I was getting weird behaviour like `@assert (I * B') == B'` failing where `I` is the identity!
